services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: tech57-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: tech57_user
      POSTGRES_PASSWORD: tech57_password
      POSTGRES_DB: gestionevenements
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - tech57-network

  ollama:
    image: ollama/ollama:latest
    container_name: tech57-ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - tech57-network

  # ENVIRONNEMENT IA (Python 3.12 conforme à votre version)
  ia:
    image: python:3.12-slim
    container_name: tech57-ia
    ports:
      - "8000:8000"
    volumes:
      - ./ia:/app
    working_dir: /app
    command: sh -c "pip install --no-cache-dir -r requirements.txt && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    networks:
      - tech57-network

  # ENVIRONNEMENT BACKEND (Java 21 conforme à votre pom.xml)
  # ENVIRONNEMENT BACKEND (Java 21)
  backend:
    image: eclipse-temurin:21-jdk
    container_name: tech57-backend
    ports:
      - "8080:8080"
    environment:
      # Surcharge automatique de l'URL pour Docker :
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/gestionevenements
      - SPRING_DATASOURCE_USERNAME=tech57_user
      - SPRING_DATASOURCE_PASSWORD=tech57_password
    volumes:
      - ./backend:/app
    working_dir: /app
    command: ./mvnw spring-boot:run
    restart: on-failure
    depends_on:
      - postgres
    networks:
      - tech57-network

# ENVIRONNEMENT FRONTEND
  frontend:
    image: node:22
    container_name: tech57-frontend
    ports:
      - "4200:4200"
    volumes:
      - ./frontend:/app
    working_dir: /app
    command: sh -c "npm install && npm start -- --host 0.0.0.0 --disable-host-check"
    networks:
      - tech57-network

volumes:
  postgres_data:
  ollama_data:

networks:
  tech57-network:
    driver: bridge