services:
  ollama:
    image: ollama/ollama:latest
    container_name: tech57-ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - tech57-network

  # ENVIRONNEMENT IA (Python 3.12)
  ia:
    image: python:3.12-slim
    container_name: tech57-ia
    ports:
      - "8000:8000"
    volumes:
      - ./ia:/app
    working_dir: /app
    command: sh -c "pip install --no-cache-dir -r requirements.txt && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    networks:
      - tech57-network

  # ENVIRONNEMENT BACKEND (Java 21)
  backend:
    image: eclipse-temurin:21-jdk
    container_name: tech57-backend
    ports:
      - "8080:8080"
    environment:
      # Surcharge explicite de l'URL pour pointer vers Neon Cloud :
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ep-quiet-math-aglw807t-pooler.c-2.eu-central-1.aws.neon.tech/neondb?sslmode=require
      - SPRING_DATASOURCE_USERNAME=neondb_owner
      - SPRING_DATASOURCE_PASSWORD=npg_JN2sakXUmlf8
    volumes:
      - ./backend:/app
    working_dir: /app
    command: ./mvnw spring-boot:run
    restart: on-failure
    networks:
      - tech57-network

  # ENVIRONNEMENT FRONTEND
  frontend:
    image: node:22
    container_name: tech57-frontend
    ports:
      - "4200:4200"
    volumes:
      - ./frontend:/app
    working_dir: /app
    command: sh -c "npm install && npm start -- --host 0.0.0.0 --disable-host-check"
    networks:
      - tech57-network

volumes:
  ollama_data:

networks:
  tech57-network:
    driver: bridge