# Port de l'application Spring Boot
server.port=8080

# Configuration de la base de donnees PostgreSQL (Neon)
spring.datasource.url=jdbc:postgresql://ep-quiet-math-aglw807t-pooler.c-2.eu-central-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_JN2sakXUmlf8
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuration JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT
jwt.secret=qb9AmYgY9ZsJZcGNecYatWXIX+rGPBTRrn6EN4IEPa38+xhYMcfcVq2dIgNPgbD5QRLOBQzL8nxkSx38hQ7+7w==
jwt.access-token-expiration-ms=1800000
jwt.refresh-token-expiration-ms=604800000
app.cors.allowed-origins=http://localhost:4200
app.base-url=http://localhost:8080

#Neon
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=10000
spring.datasource.hikari.max-lifetime=25000
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.keepalive-time=15000
spring.datasource.hikari.validation-timeout=5000

# Dossier physique de stockage (hors classpath, persistant)
app.upload.dir=./uploads

# Limites Spring pour multipart
spring.servlet.multipart.max-file-size=25MB
spring.servlet.multipart.max-request-size=25MB

#ressources observateur
app.storage.documents-path=ia/data

#forget pwd
# Mail (SMTP) - reset password
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=houbbadiassia@gmail.com
spring.mail.password=evcz mrzi lhaw eclj
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

app.frontend-url=http://localhost:4200